# Generated by Django 6.1 on 2026-09-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mahasiswa_alter_experience_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill_type', models.CharField(choices=[('Software', 'Software Development'), ('Systems', 'Systems & Architecture')], max_length=20)),
                ('description', models.TextField()),
                ('image_filename', models.CharField(help_text="Contoh: 'img/java_logo.png' atau 'image_127101.png'", max_length=200)),
            ],
        ),
    ]
